# Generated by Django 4.2.16 on 2024-10-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="humidity",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(default=0),
        ),
    ]
