# Generated by Django 4.2.16 on 2024-10-23 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatherdata_humidity_weatherdata_wind_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("avg_temp", models.FloatField()),
                ("max_temp", models.FloatField()),
                ("min_temp", models.FloatField()),
                ("avg_humidity", models.FloatField()),
                ("max_wind_speed", models.FloatField()),
                (
                    "dominant_weather",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
